gcc -D_REENTRANT task6.c -o task6 -lpthread
./task6
#thread_function is running...
#Thread is still running (0)...
#Thread is still running (1)...
#Thread is still running (2)...
#Thread is still running (3)...
#Canceling thread...
#Waiting for thread to finished...
